version: "3"
services:

    # MySQL Service
    mysql:
        image: 'mysql/mysql-server:5.7.31'
        container_name: "${PROJECT_NAME}_mysql"
        tty: true
        environment:
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASS_ROOT}
            MYSQL_ROOT_HOST: '%'
            SERVICE_NAME: mysql
        ports: 
            - '3306:3306'
        volumes:
            - ./docker/mysql/dbdata/:/var/lib/mysql-files/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - private

    # Backend (PHP)
    back:
        build:
            context: .
            dockerfile: ./docker/back/Dockerfile
        container_name: "${PROJECT_NAME}_back"
        tty: true
        environment:
            SERVICE_NAME: back
        working_dir: /var/www/html
        ports:
            - "8080:80"
        volumes:
            - laravel-storage:/var/www/html/storage
        networks:
            - private
        depends_on:
            - mysql

    # Frontend
    front:
        build:
            context: .
            dockerfile: ./docker/front/Dockerfile
        container_name: "${PROJECT_NAME}_front"
        tty: true
        ports: 
            - '8088:80'
        depends_on:
            - back

volumes:
    laravel-storage:
        driver: local
networks:
    private:
        driver: bridge